// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxXsCUwiHQY3DBBFp_i5h5Yu5jDRsxKjg',
    appId: '1:102387243770:web:5ed9861dfa9479f0b90743',
    messagingSenderId: '102387243770',
    projectId: 'loginexample-854ac',
    authDomain: 'loginexample-854ac.firebaseapp.com',
    storageBucket: 'loginexample-854ac.firebasestorage.app',
    measurementId: 'G-6TW4WL32Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqvM-NY_zgD9Wrlu385rce8SEZzQuz8Zg',
    appId: '1:102387243770:android:4cb0c5c3ee740f4eb90743',
    messagingSenderId: '102387243770',
    projectId: 'loginexample-854ac',
    storageBucket: 'loginexample-854ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEd_VhWO7r9y4_B3fYHO-ZrwB5QPulJ28',
    appId: '1:102387243770:ios:6d5e741964224f91b90743',
    messagingSenderId: '102387243770',
    projectId: 'loginexample-854ac',
    storageBucket: 'loginexample-854ac.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginGoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEd_VhWO7r9y4_B3fYHO-ZrwB5QPulJ28',
    appId: '1:102387243770:ios:6d5e741964224f91b90743',
    messagingSenderId: '102387243770',
    projectId: 'loginexample-854ac',
    storageBucket: 'loginexample-854ac.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginGoogle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxXsCUwiHQY3DBBFp_i5h5Yu5jDRsxKjg',
    appId: '1:102387243770:web:44aa9f1143bbbca8b90743',
    messagingSenderId: '102387243770',
    projectId: 'loginexample-854ac',
    authDomain: 'loginexample-854ac.firebaseapp.com',
    storageBucket: 'loginexample-854ac.firebasestorage.app',
    measurementId: 'G-1ZS1R8RRS8',
  );
}
